### ISSUE TITLE
mean_FA_* not saved in the outDir when 'ENIGMA' template has been used

### ISSUE THREAD

**Issue by kcho** [pnlbwh/TBSS#11]
Using `--ENIGMA` argument in `tbss_all` lead to the logic at skeletonize.py, line 202
```py
if (args.skeleton and args.skeletonMask and args.skeletonMaskDst):
    print('All are here ****')
    sys.exit('All are here***')
```

It currently does not copy `args.skeleton`, `args.skeletonMask`, `args.skeletonMaskDst` into the `outDir`. 

Are we not copying the ENIGMA mean skeleton files into the `outDir`?

**Comment by tashrifbillah** [comment]
That's correct, we are not. Only created template images are saved in ---outDir. To know location of default templates, look at the `log/command.txt`. However, if I think Ofer requested them to be copied over to --outDir. Our rational behind not doing that is to save some space and avoid data duplication.
