### ISSUE TITLE
input tbss_skeleton for ENIGMA project is documented as individual FA files

### ISSUE THREAD

**Issue by kcho** [pnlbwh/TBSS#13]
https://github.com/pnlbwh/TBSS/blob/0bb89f4485db7a91d088ccd99e01024a0521a4e8/lib/project_skeleton.py#L48-L63

In the ENIGMA TBSS protocol, page 3 - http://enigma.ini.usc.edu/wp-content/uploads/DTI_Protocols/ENIGMA_TBSS_protocol_USC.pdf
, `tbss_skeleton` uses individual subjects’ FA map as the input. General TBSS(`tbss_4_prestats`) and `project_skeleton.py` uses mean_FA.nii.gz as the input for tbss_skeleton. The output skeleton is different.
 

test
---

**ENIGMA style tbss_skeleton**
`tbss_skeleton -i FA.nii.gz -p 0.049 /data/pnl/soft/pnlpipe3/tbss/data/enigmaDTI/ENIGMA_DTI_FA_skeleton_mask_dst.nii.gz /data/pnl/soft/pnlpipe3/fsl/data/standard/LowerCingulum_1mm.nii.gz FA.nii.gz enigma_out.nii.gz -s /data/pnl/soft/pnlpipe3/tbss/data/enigmaDTI/ENIGMA_DTI_FA_skeleton_mask.nii.gz`
 
**FSL TBSS style (tbss_4) tbss_skeleton - what `project_skeleton.py` uses**
`tbss_skeleton -i mean_FA.nii.gz -p 0.049 /data/pnl/soft/pnlpipe3/tbss/data/enigmaDTI/ENIGMA_DTI_FA_skeleton_mask_dst.nii.gz /data/pnl/soft/pnlpipe3/fsl/data/standard/LowerCingulum_1mm.nii.gz FA.nii.gz mean_FA_out.nii.gz -s /data/pnl/soft/pnlpipe3/tbss/data/enigmaDTI/ENIGMA_DTI_FA_skeleton_mask.nii.gz`
 
**Difference between output maps**
`fslmaths enigma_out.nii.gz -sub mean_FA_input_out.nii.gz diff.nii.gz`
`fslstats diff.nii.gz -M`
0.034381
 
As Ofer mentioned, we have to go through tbss_skeleton.cc to decide which input to use.
As you expect, I’m very slow reading c++ script, but I see that curvature and CofG are estimated in the input file. Maybe this is causing the discrepancy.
I’ll try to understand the script a little more over the weekends.

@OferPasternak @tashrifbillah

**Comment by tashrifbillah** [comment]
Difference between FSL and ENIGMA projection documented below:

https://github.com/pnlbwh/TBSS/commit/02baa7a631ab74df2db6c981b2511e0e0e905c0b

**Comment by tashrifbillah** [comment]
Individual FA for all branches:

> res.append(pool.apply_async(project_skeleton, (c, imgPath, args, skelDir)))

Before it was
 
> res.append(pool.apply_async(project_skeleton, (c, imgPath, args, meaFA, skelDir)))

https://github.com/pnlbwh/TBSS/commit/6ade36aa2872b810f76f64617ef9fe5567e793e3

**Comment by tashrifbillah** [comment]
Update test data
https://github.com/pnlbwh/TBSS/commit/b51b7e8abc8ea6698c3d36571c9c37e6e1c5aaaa

**Comment by tashrifbillah** [comment]
https://github.com/pnlbwh/TBSS/pull/17
