### ISSUE TITLE
input to the `tbss_skeleton` for non-FA images

### ISSUE THREAD

**Issue by kcho** [pnlbwh/TBSS#37]
are we using non-FA image itself to the `-i` option to the tbss_skeleton for skeletonizing non-FA images? shouldn't input to the `-i` be FA image?

https://github.com/pnlbwh/TBSS/blob/f9a271130d27407df24e7c858cb26dbae60865c6/lib/project_skeleton.py#L61-L67

**Comment by tashrifbillah** [comment]
The changes was introduced [here](https://github.com/pnlbwh/TBSS/commit/6ade36aa2872b810f76f64617ef9fe5567e793e3#diff-88d525ef2b810e60a6e44619c3c800d1) following your issue https://github.com/pnlbwh/TBSS/issues/13.

But I understand you are referring to what it was before your issue. I am comparing with FSL and ENIGMA documentation.

**Comment by kcho** [comment]
my issue in https://github.com/pnlbwh/TBSS/issues/13 was comparing `mean_FA` and individual `FA` as the input to the `-i` option in tbss_skeleton. Here the `line 63` is taking the `non-FA` image itself as the input for the `-i`. Correct?

**Comment by tashrifbillah** [comment]
> Here the line 63 is taking the non-FA image itself as the input for the -i. Correct?

Yes.

> shouldn't input to the -i be FA image?

It looks like we hit a snag. I kept you in the loop about PR #17 though that [substituted](https://github.com/pnlbwh/TBSS/pull/17/commits/6ade36aa2872b810f76f64617ef9fe5567e793e3) `meanFA` by nonFA `imgPath`

**Comment by tashrifbillah** [comment]
Let's hear your suggestion, should we change the block you referenced to something like:
```
cmd= (' ').join(['tbss_skeleton', 
                  '-i', imgPathOfFA, 
                  '-p', args.SKEL_THRESH, args.skeletonMaskDst, args.SEARCH_RULE_MASK, 
                  pjoin(args.outDir, 'FA', 'warped', f'{c}_FA_to_target.nii.gz'), 
                  modImgSkel, '-a', imgPath, 
                  '-s', args.skeletonMask])
```

Notice the first `imgPath` changed to `imgPathOfFA`.

**Comment by kcho** [comment]
> It looks like we hit a snag. I kept you in the loop about PR #17 though that substituted meanFA by nonFA imgPath

I'm sorry I have not been following all the changes that were merged. I think Ofer and Sylvain +people who are currently using this pipeline should be notified, which may require re-analysis.

**Comment by kcho** [comment]
> Let's hear your suggestion, should we change the block you referenced to something like:
> 
> ```python
> cmd= (' ').join(['tbss_skeleton', 
>                   '-i', imgPathOfFA, 
>                   '-p', args.SKEL_THRESH, args.skeletonMaskDst, args.SEARCH_RULE_MASK, 
>                   pjoin(args.outDir, 'FA', 'warped', f'{c}_FA_to_target.nii.gz'), 
>                   modImgSkel, '-a', imgPath, 
>                   '-s', args.skeletonMask])
> ```
> 
> Notice the first `imgPath` changed to `imgPathOfFA`.

Yes, you should confirm with Ofer one more time.

**Comment by tashrifbillah** [comment]
Before we do that, I am going to take a look at `tbss_non_FA` script by FSL.

**Comment by tashrifbillah** [comment]
> Yes, you should confirm with Ofer one more time.

Is the new confusion about using `imgPathOfFA` vs `meanFA` for the nonFA block?

**Comment by tashrifbillah** [comment]
Fixed by https://github.com/pnlbwh/TBSS/commit/7d647a7a4ce0556d8df1c7cfb64b9b5f4c6bc10d
