### ISSUE TITLE
ValueError: I/O operation on closed file

### ISSUE THREAD

**Issue by cooperr11** [pnlbwh/TBSS#42]
Hi there,

Our group is having trouble running the TBSS pipeline on greater than 4 participants. The program will complete with 4 participants, but when tested with >4 participants, the program fails with the error:
"ValueError: I/O operation on closed file."
This occurs with all of the options (eg --fmrib, --enigma, --studyTemplate).

Attached is the log file for n=5 participants using the --fmrib template.

[log_fmrib_030.txt](https://github.com/pnlbwh/TBSS/files/4969877/log_fmrib_030.txt)

Thanks,
Bec

**Comment by tashrifbillah** [comment]
Hi @cooperr11, the following is your traceback that we need to sort out this issue.

```vim
Total elapsed time: 255
fixedImage: /usr/local/fsl_v6.0.1/data/standard/FMRIB58_FA_1mm.nii.gz, movingImage: /data/netapp01/work/Rebecca_Cooper/testingADS/tbss_fmrib_030/FA/preproc/1005031_FA.nii.gz
fixedImage: /usr/local/fsl_v6.0.1/data/standard/FMRIB58_FA_1mm.nii.gz, movingImage: /data/netapp01/work/Rebecca_Cooper/testingADS/tbss_fmrib_030/FA/preproc/1005034_FA.nii.gz
fixedImage: /usr/local/fsl_v6.0.1/data/standard/FMRIB58_FA_1mm.nii.gz, movingImage: /data/netapp01/work/Rebecca_Cooper/testingADS/tbss_fmrib_030/FA/preproc/1005032_FA.nii.gz
fixedImage: /usr/local/fsl_v6.0.1/data/standard/FMRIB58_FA_1mm.nii.gz, movingImage: /data/netapp01/work/Rebecca_Cooper/testingADS/tbss_fmrib_030/FA/preproc/1005033_FA.nii.gz
Exception in thread Thread-6:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/cooperr/miniconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/cooperr/tbss/lib/antsTemplate.py", line 57, in antsReg
    print(f'fixedImage: {fixedImg}, movingImage: {movingImg}')
ValueError: I/O operation on closed file.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/cooperr/miniconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/cooperr/miniconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/cooperr/miniconda3/lib/python3.7/multiprocessing/pool.py", line 486, in _handle_results
    cache[job]._set(i, obj)
  File "/Users/cooperr/miniconda3/lib/python3.7/multiprocessing/pool.py", line 664, in _set
    self._error_callback(self._value)
  File "/Users/cooperr/tbss/lib/tbssUtil.py", line 68, in RAISE
    raise ERR
ValueError: I/O operation on closed file.
```

**Comment by tashrifbillah** [comment]
You can try a few things:

* Rerun with `-n 2` processors only.
* make sure your have 8 GB RAM at least

In addition, what's the command you tried?

**Comment by tashrifbillah** [comment]
Hi @cooperr11 , can you delete the output directory and try again without the `--verbose` flag? I believe you had that in the previous attempt. I am not sure if there is a bug with that flag but we shall know if you omit that and retry.

**Comment by tashrifbillah** [comment]
If that does not solve your problem, try with `-n 2`.
Also, provide the command you tried.

**Comment by cooperr11** [comment]
Hi @tashrifbillah,

Thank you for your reply. 
The command I usually run:
~/tbss/lib/tbss_all --modality FA -i FA_20 --caselist subjects_20.txt --fmrib --verbose

I tried without --verbose as well as with -n 2. I received the following error:

[log.txt](https://github.com/pnlbwh/TBSS/files/4977253/log.txt)

Thanks!

**Comment by tashrifbillah** [comment]
You are missing `-o`.

**Comment by cooperr11** [comment]
Apologies. That was NOT the usual command.

I tried without --verbose and with --fmrib; so far it runs with n=20 subjects.
However, it will not run with the --studytemplate option.

Command:  ~/tbss/lib/tbss_all --modality FA -i FA_20 --studyTemplate &>log.txt -o tbss_20_studytemplate
_log -c subjects_20.txt

See log:
[log.txt](https://github.com/pnlbwh/TBSS/files/4979002/log.txt)

Thanks.

**Comment by tashrifbillah** [comment]
See if the following helps:

> ~/tbss/lib/tbss_all --modality FA -i FA_20 --studyTemplate -o tbss_20_studytemplate_log -c subjects_20.txt > log.txt 2>&1

Once again, delete the `tbss_20_studytemplate_log` first.

**Comment by cooperr11** [comment]
Thanks @tashrifbillah. It appears to have worked (?). The log file says that the processing is complete, and I can view the .png images at ../tbss_20_studytemplate/FA/preproc/slicesdir. 
However, the script is still running... is this normal? 
Thanks!

**Comment by tashrifbillah** [comment]
The program is complete once html files are created in `outDir/slicesdir` for all modalities specified by `--modality`.

**Comment by tashrifbillah** [comment]
So what really was the error for you-- providing `--verbose` option?

**Comment by cooperr11** [comment]
Yes it seems so! What a simple fix. Thank you so much!

**Comment by tashrifbillah** [comment]
Interesting finding! I couldn't reproduce the issue at my end though. Thanks anyway.

**Comment by cooperr11** [comment]
Hi again @tashrifbillah, 
While I thought the problem was fixed, I realised that the directory structure wasn't as you mentioned. I was looking at the directory outDir/FA/preprocessing/slicesdir rather than outDir/FA/slicesdir. (I'm only using the --modality FA).

I noticed when I killed the script, the log file updated to print an error message, see attached: 
command: -i FA_combined --modality FA -o tbss_combined_studytemplate -c subjects_combined.txt --studyTemplate > log_studytemplate.txt 2>&1
[log_studytemplate.txt](https://github.com/pnlbwh/TBSS/files/4991201/log_studytemplate.txt)

Thanks!

**Comment by cooperr11** [comment]
*I also ran this with the same command but using the --fmrib option; this appeared to work (i.e. the html files were produced in outDir/FA/slicedir). So it appears to be specific to the --studyTemplate option.

**Comment by tashrifbillah** [comment]
@cooperr11 , let's learn to find the error message and post that only here on GitHub:
```vim
Now running "slicesdir" to generate report of all input images
Finished. To view, point your web browser at
file:/data/netapp01/work/Rebecca_Cooper/testingADS/tbss_combined_studytemplate/FA/FA/slicesdir/index.html
ps: illegal option -- -
usage: ps [-AaCcEefhjlMmrSTvwXx] [-O fmt | -o fmt] [-G gid[,gid...]]
          [-g grp[,grp...]] [-u [uid,uid...]]
          [-p pid[,pid...]] [-t tty[,tty...]] [-U user[,user...]]
       ps [-L]
Preprocessing FA images: eroding them and zeroing the end slices ...
```

However, I haven't seen this error before. 

Try a few things:

1. Try to open this file on your webbrowser, it will help us understand if `slicesdir` command worked fine or not:
/data/netapp01/work/Rebecca_Cooper/testingADS/tbss_combined_studytemplate/FA/FA/slicesdir/index.html

2. See if files are created for all 20 of your cases in `FA/origdata`, `FA/preproc` , etc.

Question, is the problem happening for `--studyTemplate` branch only?

To reiterate, remove any previous outputs before retrying.

**Comment by cooperr11** [comment]
Sorry. I'm new to github!
1. the directory doesn't exist. Within the /data/netapp01/work/Rebecca_Cooper/testingADS/tbss_combined_studytemplate/FA/ folder, there lies the files:
.tbsslog  origdata/ preproc/  roi/      skeleton/ warped/
2. Files were created for my cases only within the folders origdata/ and preproc/. The remaining folders (roi/, skeleton/ and /warped) were empty.
3. Confirmed, only for --studyTemplate.

**Comment by tashrifbillah** [comment]
Unfortunately, I can't reproduce this issue at my end. Also, it is wired that other branches run without trouble except `--studyTemplate`. Anyways, try the `--studyTemplate` branch fresh again with `--verbose` enabled and provide full log like you have done before.

**Comment by cooperr11** [comment]
Hi @tashrifbillah, sorry about the delay in replying.
Using the following command:
~/tbss/lib/tbss_all -i FA_test -c caselist32.txt --modality FA --studyTemplate -o tbss_test_studytemplate

I receive the following error:
Exception in thread Thread-6:
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
File "/Users/cooperr/miniconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker 
result = (True, func(*args, **kwds))
File "/Users/cooperr/tbss/lib/shellCmds.py", line 18, in _antsApplyTransforms     print(f'Warping {imgPath} to template space ...')
ValueError: I/O operation on closed file.

**Comment by tashrifbillah** [comment]
Again, it's probably related to RAM shortage in your host. Someone might be killing the job due to RAM exceeding a threshold. Higher performance cluster admins usually have such check in place.

Another reason could be disk space shortage. Make sure you have enough space where you write `tbss_test_studytemplate`. 

As before, you can try with `-n 2`, using only 2 CPUs would reduce memory consumption a bit. The default option attempts to use 4 CPUs.

**Comment by cooperr11** [comment]
Thanks, it works with a newer machine in our imaging lab and n=2. I guess it's a CPU related problem then!

Thanks so much for helping us troubleshoot this process, @tashrifbillah. We really appreciate all your help!

**Comment by tashrifbillah** [comment]
You are welcome @cooperr11 . It seems that n>2 should also work on that newer machine.
