### ISSUE TITLE
suggestion: providing `--xfrmDir` option overwrites the path given to the `--outdir` option

### ISSUE THREAD

**Issue by kcho** [pnlbwh/TBSS#43]
Hi Tashrif,

In running non-FA TBSS using `--xfrmDir` option, the **commandline given** `--outdir` gets replaced by the previous `--outdir` path stored in the `log/command.txt`. This still leads to a new directory at the **commandline given** `--outdir` path, while the actual `skeletonization` outputs get saved in the *previous* `--outdir` from the `log/command.txt`.

#### commandline given `outDir` path gets created
https://github.com/pnlbwh/TBSS/blob/663cd5b756344d9bab68e18e4fd4d9e3f16bfc02/lib/tbss_all#L159-L162

#### args.outDir gets overwritten with the `dirname(args.xfrmDir)`, so the output goes here.
https://github.com/pnlbwh/TBSS/blob/663cd5b756344d9bab68e18e4fd4d9e3f16bfc02/lib/tbss_all#L179-L186

Same goes for the `args.logDir`.

I think it could be useful to keep `args.outDir` as the commandline given path, and only use `dirname(args.xfrmDir)` if `--outdir` was not used.

```py
    # line 179 in tbss_all
    if not args.xfrmDir:
        args.xfrmDir = pjoin(args.outDir, 'transform')


    else:
        args.xfrmDir = abspath(args.xfrmDir)
        warn(f'Running separate nonFA TBSS, with same settings of previous FA TBSS')
        if args.outDir:
            pass
        else:
            args.outDir = dirname(args.xfrmDir)
            args.logDir = pjoin(args.outDir, 'log')
```

**Comment by tashrifbillah** [comment]
Hi @kcho , is the discrepancy that although `args.outDir = dirname(args.xfrmDir)` is used, the new `--outDir` gets stored in the log?

**Comment by kcho** [comment]
Hi @tashrifbillah 

the commandline given `--outDir` directory first gets created, then the`args.outDir = dirname(args.xfrmDir)` follows, making the actual output to go inside `dirname(ars.xfrmDir)`

What are your thoughts on saving the outputs to the commandline given `--outDir` path (if `--outDir` is given)?

**Comment by tashrifbillah** [comment]
All outputs should go to `dirname(args.xfrmDir)`. Having FA output in `args.ourDir` initially and nonFA outputs in a different `--outDir` can be messy, which is the philosophy we considered when developing this software.

> the commandline given --outDir directory first gets created

I shall look into this. If `--outDir` is provided for nonFA, it should be totally ignored--won't be created or logged.

**Comment by kcho** [comment]
I personally think saving outputs to `--outDir`, if it's given by the user, would be useful. I would think a user is highly likely to try to give `--outDir`, which is a common practice for many other commands, where the current design may confuse users who give `--outDir` to the commandline.

**Comment by tashrifbillah** [comment]
Okay, but it must be the same `--outDir` as before. Otherwise, we must raise an error.

**Comment by kcho** [comment]
Okay, I see that we're trying to force `tbss` output directories as clear and simple as possible. I just thought there could be times when a user wanted to save it to another directory than the previous `tbss` directory.

**Comment by tashrifbillah** [comment]
PR to follow through shortly ...

**Comment by tashrifbillah** [comment]
For nonFA TBSS, **commandline given** different `-o` is no longer created. It is checked for consistency with that of previous FA TBSS on top and rejected if not.

PR https://github.com/pnlbwh/TBSS/pull/44
