### ISSUE TITLE
ROI on whole-brain images

### ISSUE THREAD

**Issue by bmol239** [pnlbwh/TBSS#56]
Is it possible to use this pipeline to run ROI analysis on whole-brain images, as opposed to just the skeletonised images? Thanks!

**Comment by tashrifbillah** [comment]
See if you can hack it.

**Comment by tashrifbillah** [comment]
This program may be of interest to you:

**Comment by tashrifbillah** [comment]
This program may be of interest to you:
https://github.com/pnlbwh/pnlNipype/blob/master/scripts/DWIqc/dwi_quality.py
