### ISSUE TITLE
 error and freeze when running tests within a docker

### ISSUE THREAD

**Issue by fabioboh** [pnlbwh/TBSS#58]
dear developers,

I have created a docker for tbss that is based on python 3.11. When running the tests I get the following error:

`(base) root@77b1fa886927:/app/tbss# ./install.sh test
Preparing to run TBSS pipeline tests ...
FA,MD,AD,RD modality TBSS are run on four dwi/mask pairs
Running multi-modality TBSS pipeline tests should take less than an hour
/app/tbss /app/tbss
Fetching test data ...
/app/tbss/lib/tests/data /app/tbss/lib/tests/data /app/tbss
Generating brain mask for test data ...
/app/tbss/lib/tests/data /app/tbss
Testing --enigma branch ...

# ===============================================================================
# tbss (2019) pipeline is written by-
# 
# TASHRIF BILLAH
# Brigham and Women's Hospital/Harvard Medical School
# tbillah@bwh.harvard.edu
# 
# ===============================================================================
# See details at https://github.com/pnlbwh/tbss
# Submit issues at https://github.com/pnlbwh/tbss/issues
# View LICENSE at https://github.com/pnlbwh/tbss/blob/master/LICENSE
# ===============================================================================
# __version__ 0.1.5

antsApplyTransforms found
antsRegistrationSyNQuick.sh found
antsMultivariateTemplateConstruction2.sh found
antsRegistration found
dtifit found
tbss_1_preproc found
tbss_skeleton found
distancemap found
All executables are found, program will begin now ...
/app/tbss/lib/tbssUtil.py:58: UserWarning: /app/tbss/lib/tests/enigmaTemplateOutput/stats exists and will be overwritten
  warn(f'{dir} exists and will be overwritten')
--enigma template specified, using http://enigma.ini.usc.edu/wp-content/uploads/2013/02/enigmaDTI.zip provided templates
/app/tbss/lib/tbssUtil.py:58: UserWarning: /app/tbss/lib/tests/enigmaTemplateOutput/FA exists and will be overwritten
  warn(f'{dir} exists and will be overwritten')
/app/tbss/lib/tbssUtil.py:58: UserWarning: /app/tbss/lib/tests/enigmaTemplateOutput/MD exists and will be overwritten
  warn(f'{dir} exists and will be overwritten')
/app/tbss/lib/tbssUtil.py:58: UserWarning: /app/tbss/lib/tests/enigmaTemplateOutput/AD exists and will be overwritten
  warn(f'{dir} exists and will be overwritten')
/app/tbss/lib/tbssUtil.py:58: UserWarning: /app/tbss/lib/tests/enigmaTemplateOutput/RD exists and will be overwritten
  warn(f'{dir} exists and will be overwritten')
/app/tbss/lib/tbss_all:453: UserWarning: Assuming cases in --caselist correspond to images in --input, make sure they are ordered correctly
  warn('Assuming cases in --caselist correspond to images in --input, make sure they are ordered correctly')
DIPY dtifit  /app/tbss/lib/tests/data/dcm_qa_uih/Ref/dti_tra_dir16_AP_9_134431.nii
DIPY dtifit  /app/tbss/lib/tests/data/dcm_qa_uih/Ref/dti_tra_dir16_PA_6_134431.nii
DIPY dtifit  /app/tbss/lib/tests/data/dcm_qa_uih/Ref/dti_tra_dir16_PA_rot_12_132222.nii
DIPY dtifit  /app/tbss/lib/tests/data/dcm_qa_uih/Ref/dti_tra_dir16_PA_rot_12_134431.nii

TBSS for modality  FA
Preprocessing FA images: eroding them and zeroing the end slices ...
processing dti_tra_dir16_AP_9_134431
processing dti_tra_dir16_PA_6_134431
processing dti_tra_dir16_PA_rot_12_132222
processing dti_tra_dir16_PA_rot_12_134431
Now running "slicesdir" to generate report of all input images
Finished. To view, point your web browser at
file:/app/tbss/lib/tests/enigmaTemplateOutput/FA/FA/slicesdir/index.html
Index file location has changed, see  /app/tbss/lib/tests/enigmaTemplateOutput/FA/preproc/slicesdir/index.html
Registering FA images to /app/tbss/data/enigmaDTI/ENIGMA_DTI_FA.nii.gz space ..
/app/tbss/lib/tbssUtil.py:58: UserWarning: /app/tbss/lib/tests/enigmaTemplateOutput/transform exists and will be overwritten
  warn(f'{dir} exists and will be overwritten')
fixedImage: /app/tbss/data/enigmaDTI/ENIGMA_DTI_FA.nii.gz, movingImage: /app/tbss/lib/tests/enigmaTemplateOutput/FA/preproc/dti_tra_dir16_AP_9_134431_FA.nii.gz
fixedImage: /app/tbss/data/enigmaDTI/ENIGMA_DTI_FA.nii.gz, movingImage: /app/tbss/lib/tests/enigmaTemplateOutput/FA/preproc/dti_tra_dir16_PA_6_134431_FA.nii.gz
fixedImage: /app/tbss/data/enigmaDTI/ENIGMA_DTI_FA.nii.gz, movingImage: /app/tbss/lib/tests/enigmaTemplateOutput/FA/preproc/dti_tra_dir16_PA_rot_12_132222_FA.nii.gz
fixedImage: /app/tbss/data/enigmaDTI/ENIGMA_DTI_FA.nii.gz, movingImage: /app/tbss/lib/tests/enigmaTemplateOutput/FA/preproc/dti_tra_dir16_PA_rot_12_134431_FA.nii.gz
Exception in thread Thread-6 (_handle_results):
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/envs/tbss_env/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/app/tbss/lib/antsTemplate.py", line 80, in antsReg
    remove(outPrefix+'Warped.nii.gz')
FileNotFoundError: [Errno 2] No such file or directory: '/app/tbss/lib/tests/enigmaTemplateOutput/transform/dti_tra_dir16_PA_6_134431_FAWarped.nii.gz'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/tbss_env/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/tbss_env/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/tbss_env/lib/python3.11/multiprocessing/pool.py", line 595, in _handle_results
    cache[job]._set(i, obj)
  File "/opt/conda/envs/tbss_env/lib/python3.11/multiprocessing/pool.py", line 781, in _set
    self._error_callback(self._value)
  File "/app/tbss/lib/tbssUtil.py", line 68, in RAISE
    raise ERR
FileNotFoundError: [Errno 2] No such file or directory: '/app/tbss/lib/tests/enigmaTemplateOutput/transform/dti_tra_dir16_PA_6_134431_FAWarped.nii.gz'

`

after this is printed on screen the program freezes. I think the file dti_tra_dir16_PA_6_134431_FAWarped.nii.gz should be created by the test itself, so I am surprised it is not there, since there is no error before. do you have any hint that could help me debug this?

the folder /app/tbss/lib/tests/enigmaTemplateOutput/transform is empty after interrupting the above execution with Ctrl+C

thanks

**Comment by fabioboh** [comment]
I also noticed some possible mistakes in the install.sh script:

at line 165:
cd $testDir/enigmaTemplateOutput/


shouldn t be
cd $testDir/fmribTemplateOutput/


and at line 193

shouldn t it be
cd $testDir/studyTemplateOutput/

**Comment by fabioboh** [comment]
when I try to execute the tests singularly, for example for the fmrib I get a segmentation fault:



(base) root@77b1fa886927:/app/tbss/lib/tests/enigmaTemplateOutput# /app/tbss/lib/tbss_all -i FA/origdata,MD,AD,RD -c /app/tbss/lib/tests/data/caselist.txt --modality FA,MD,AD,RD --studyTemplate -s $FSLDIR/data/standard/FMRIB58_FA_1mm.nii.gz -l $FSLDIR/data/atlases/JHU/JHU-ICBM-labels-1mm.nii.gz --lut $testDir/data/FreeSurferColorLUT.txt --avg -o $testDir/studyTemplateOutput/ --noFillHole --ncpu 1 --force


...

TBSS for modality  FA
Preprocessing FA images: eroding them and zeroing the end slices ...
processing dti_tra_dir16_AP_9_134431
processing dti_tra_dir16_PA_6_134431
processing dti_tra_dir16_PA_rot_12_132222
processing dti_tra_dir16_PA_rot_12_134431
Now running "slicesdir" to generate report of all input images
Finished. To view, point your web browser at
file:/app/tbss/lib/tests/studyTemplateOutput/FA/FA/slicesdir/index.html
Index file location has changed, see  /app/tbss/lib/tests/studyTemplateOutput/FA/preproc/slicesdir/index.html
Creating study specific template ...
See /app/tbss/lib/tests/studyTemplateOutput/log/template_construct.log for details of template construction
/app/tbss/lib/antsMultivariateTemplateConstruction2_fixed_random_seed.sh: line 270: 18306 Segmentation fault      (core dumped) ${ANTSPATH}/AverageImages $dim $output 1 ${images[*]}

**Comment by fabioboh** [comment]
ok now I know what it is. the test is supposed to be run after the install, which downloads enigmaDTI.zip

however, no error is produced if wget fails - which was my case.

**Comment by tashrifbillah** [comment]
For future -- instead of single ` , use triple ``` . Because of this error, your markdown did not render correctly.

**Comment by tashrifbillah** [comment]
I fixed your first comment. You fix the second one.
